Test that Typechecking Succeeds as expected
  $ copland_evidence_tools --req "$(cat Test_Req.json)"
  { "TYPE": "RESPONSE", "ACTION": "TypeCheck", "SUCCESS": true, "PAYLOAD": { "Option_Body": { "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "attest", "ASP_ARGS": {  } }, { "EvidenceT_CONSTRUCTOR": "mt_evt" }] } } }

Test that Typechecking Succeeds as expected when doing APPR too
  $ copland_evidence_tools --req "$(cat Test_Req_with_Appr.json)"
  { "TYPE": "RESPONSE", "ACTION": "TypeCheck", "SUCCESS": true, "PAYLOAD": { "Option_Body": { "EvidenceT_CONSTRUCTOR": "split_evt", "EvidenceT_BODY": [{ "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "magic_appr", "ASP_ARGS": {  } }, { "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "attest", "ASP_ARGS": {  } }, { "EvidenceT_CONSTRUCTOR": "mt_evt" }] }] }, { "EvidenceT_CONSTRUCTOR": "mt_evt" }] } } }

Test the TC succeeds with a jumbo test
  $ copland_evidence_tools --req "$(cat Test_Req_Big.json)"
  { "TYPE": "RESPONSE", "ACTION": "TypeCheck", "SUCCESS": true, "PAYLOAD": { "Option_Body": { "EvidenceT_CONSTRUCTOR": "split_evt", "EvidenceT_BODY": [{ "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "sig_appr", "ASP_ARGS": { "asp_id_appr": "sig", "targ_id_appr": "sig_targid" } }, { "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "sig", "ASP_ARGS": { "asp_id_appr": "sig", "targ_id_appr": "sig_targid" } }, { "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "hamr_readfile_range_many", "ASP_ARGS": { "asp_id_appr": "hamr_readfile_range_many", "attestation_report_filepath": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//sysml_attestation_report.json", "env_var_golden": "", "filepath_golden": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//hamr_maestro_golden_evidence.json", "report_filepath": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//sysml_attestation_report.json", "targ_id_appr": "hamr_readfile_range_many_targ" } }, { "EvidenceT_CONSTRUCTOR": "mt_evt" }] }] }] }, { "EvidenceT_CONSTRUCTOR": "split_evt", "EvidenceT_BODY": [{ "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "readfile_range_many_appr", "ASP_ARGS": { "asp_id_appr": "hamr_readfile_range_many", "attestation_report_filepath": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//sysml_attestation_report.json", "env_var_golden": "", "filepath_golden": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//hamr_maestro_golden_evidence.json", "report_filepath": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//sysml_attestation_report.json", "targ_id_appr": "hamr_readfile_range_many_targ" } }, { "EvidenceT_CONSTRUCTOR": "asp_evt", "EvidenceT_BODY": ["P0", { "ASP_ID": "hamr_readfile_range_many", "ASP_ARGS": { "asp_id_appr": "hamr_readfile_range_many", "attestation_report_filepath": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//sysml_attestation_report.json", "env_var_golden": "", "filepath_golden": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//hamr_maestro_golden_evidence.json", "report_filepath": "/Users/adampetz/Documents/Summer_2025/INSPECTA-demo/system/hamr/microkit/attestation//sysml_attestation_report.json", "targ_id_appr": "hamr_readfile_range_many_targ" } }, { "EvidenceT_CONSTRUCTOR": "mt_evt" }] }] }, { "EvidenceT_CONSTRUCTOR": "mt_evt" }] }] } } }
